name: Release

on:
  workflow_dispatch:
# Auto run on push disabled until stable version with minimum feature set.
#  push:
#    branches: [ main ]

jobs:
  release:
    needs:
      - build
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release